language: node_js

branches:
  only:
    - master

env:
  - MOZ_HEADLESS=1 NODE_OPTIONS=--max_old_space_size=8192

addons:
  firefox: latest

before_script: npm run clean && npm run patch

jobs:
  include:
    - stage: style
      node_js:
        - "10"
        - "12"
      script: npm run lint
    - stage: test
      node_js:
        - "10"
        - "12"
      script: npm run build-test && npm run test
    - stage: deploy
      if: branch = master
      node_js: "lts/*"
      script: npm run release && npx semantic-release
