language: node_js
node_js:
  - "10"
  - "12"

branches:
  only:
    - master

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_script: npm run clean && npm run build-test

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: "lts/*"
      script: npm run patch && npm run release && npx semantic-release
