/**
 * This file is auto-generated by internal gulp command.
 * If you want to customize the available gulp tasks, create your own in .tasks folder
 * and run "gulp refresh"
 */

// Default Itee tasks
export * from '@itee/tasks/sources/tests/run-tests.task.mjs'
export * from '@itee/tasks/sources/tests/units/run-unit-tests.task.mjs'
export * from '@itee/tasks/sources/tests/units/run-unit-tests-for-frontend.task.mjs'
export * from '@itee/tasks/sources/tests/units/run-unit-tests-for-backend.task.mjs'
export * from '@itee/tasks/sources/tests/units/compute-unit-tests.task.mjs'
export * from '@itee/tasks/sources/tests/bundlings/check-bundling.task.mjs'
export * from '@itee/tasks/sources/tests/bundlings/check-bundling-from-esm-files-import.task.mjs'
export * from '@itee/tasks/sources/tests/bundlings/check-bundling-from-esm-files-direct.task.mjs'
export * from '@itee/tasks/sources/tests/bundlings/check-bundling-from-esm-build-import.task.mjs'
export * from '@itee/tasks/sources/tests/benchmarks/run-benchmarks.task.mjs'
export * from '@itee/tasks/sources/tests/benchmarks/run-benchmarks-for-frontend.task.mjs'
export * from '@itee/tasks/sources/tests/benchmarks/run-benchmarks-for-backend.task.mjs'
export * from '@itee/tasks/sources/tests/benchmarks/compute-benchmarks.task.mjs'
export * from '@itee/tasks/sources/releases/release.task.mjs'
export * from '@itee/tasks/sources/patches/patch.task.mjs'
export * from '@itee/tasks/sources/lints/lint.task.mjs'
export * from '@itee/tasks/sources/helps/help.task.mjs'
export * from '@itee/tasks/sources/docs/doc.task.mjs'
export * from '@itee/tasks/sources/cleans/clean.task.mjs'
export * from '@itee/tasks/sources/builds/build.task.mjs'

