import colors            from 'ansi-colors'
import log               from 'fancy-log'
import { writeFileSync } from 'fs'
import {
    basename,
    join,
    relative
}                        from 'path'
import {
    getFilesFrom,
    packageRootDirectory
}                        from './_utils.mjs'
import { tasksToIgnore } from './configs/refresh.conf.mjs'

const {
          green,
          yellow,
      } = colors

// Get and filter tasks to expose
const taskFiles = getFilesFrom(
    join( packageRootDirectory, '.tasks/{.*.task.mjs,*.task.mjs,.**/*.task.mjs,.**/**/*.task.mjs}' ),
    filePath => {
        const relativeFilepath = relative( packageRootDirectory, filePath )
        const filename         = basename( filePath )
        const included         = !tasksToIgnore.includes( filename )

        included
        ? log( 'Include', green( relativeFilepath ) )
        : log( 'Exclude', yellow( relativeFilepath ) )

        return included
    }
)

// Prepare gulpfile content with header
let gulpfileContent = '' +
    '/**\n' +
    ' * This file is auto-generated by internal gulp command.\n' +
    ' * If you want to customize the available gulp tasks, create your own in .tasks folder\n' +
    ' * and run "gulp refresh"\n' +
    ' */\n\n'

// Generate tasks exports and append to gulpfile content
for ( const taskFile of taskFiles ) {
    const relativeTaskFile = relative( packageRootDirectory, taskFile )
    gulpfileContent += `export * from './${ relativeTaskFile }'\n`
}

// Create gulpfile file
const gulpfilePath = join( packageRootDirectory, 'gulpfile.mjs' )
log( 'Refresh', green( gulpfilePath ) )
writeFileSync( gulpfilePath, gulpfileContent )
