import colors                   from 'ansi-colors'
import log                      from 'fancy-log'
import { writeFileSync }        from 'fs'
import { glob }                 from 'glob'
import {
    join,
    normalize,
    relative
}                               from 'path'
import { packageRootDirectory } from './_utils.mjs'

const {
          blue,
          green,
          magenta,
          cyan
      } = colors

let gulpfileContent = '' +
    '/**\n' +
    ' * This file is auto-generated by internal gulp command.\n' +
    ' * If you want to customize the available gulp tasks, create your own in .tasks folder\n' +
    ' * and run "gulp refresh"\n' +
    ' */\n\n'

const taskFiles = glob.sync( join( packageRootDirectory, '.tasks/{.*.task.mjs,*.task.mjs,.**/*.task.mjs,.**/**/*.task.mjs}' ) )
                      .map( filePath => normalize( filePath ) )

for ( const taskFile of taskFiles ) {
    const module = await import(taskFile)

    const exportStrings = []
    for ( const moduleKey in module ) {
        const task         = module[ moduleKey ]
        const name         = task.name ?? null
        const displayName  = task.displayName ?? null
        const fullName     = ( moduleKey !== name ) ? `${ blue( moduleKey ) }( ${ magenta( name ) } )` : `${ blue( name ) }`
        const exportAs     = ( displayName ) ? ` as ${ cyan( displayName ) }` : ''
        const exportString = fullName + exportAs
        exportStrings.push( exportString )
    }

    const relativeTaskFile = relative( packageRootDirectory, taskFile )
    log( 'Found', green( relativeTaskFile ), 'with', exportStrings.join( ', ' ) )
    gulpfileContent += `export * from './${ relativeTaskFile }'\n`
}

const gulpfilePath = join( packageRootDirectory, 'gulpfile.mjs' )
log( 'Refreshing', green( gulpfilePath ) )
writeFileSync( gulpfilePath, gulpfileContent )
