# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Itee-Database CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MOZ_HEADLESS: 1
    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x ]
        firefox: [ 'latest' ]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Firefox ${{ matrix.firefox }}
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}
      - name: Checkout ${{ env.GITHUB_REPOSITORY }}
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npm run lint && npm run build && npm run build-test && npm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Checkout ${{ env.GITHUB_REPOSITORY }}
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        run: npm run clean && npm run lint && npm run doc && npm run build && npx semantic-release
